[build]
  # Directory with the frontend React app
  base = "frontend"
  
  # Build command for React
  command = "npm run build"
  
  # Directory to publish (React creates 'build' folder)
  publish = "frontend/build"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"

# Redirect rules for React Router (if you use it)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"