services:
  - type: web
    name: notes-app-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: notes-app-backend
          property: port
      - key: MONGODB_URI
        sync: false  # This will need to be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true
    branch: main
    rootDir: /